### ISSUE TITLE
Fix overlapping roles in AzureDevOps that leads to unexpected permissions

### ISSUE THREAD

**Issue by julie-ng** [Azure/devops-governance#12]
## Problem

There is a bug in the concept as it currently exists. As of today we rely on 2 AAD groups for actors, e.g. for the "Veggies" team, we have:

| AAD Group name | Membership |
|:--|:--|
| `veggies` | **All** developers in team |
| `veggies-admins` |  A **subset** of users who have elevated permissions |

### Expected Result

The veggie admins have elevated privileges, e.g. Administrator Access even if they have overlapping role assignments (due to membership in multiple groups).

### Actual Result

- As expected: for Azure Resource Manager, `veggie-admins` will have Administrative permissions due to ARM's [additive permissions model](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview#multiple-role-assignments)
- Unexpectedly: in Azure DevOps, `veggie-admins` will only have _Contributor_ access because Azure DevOps uses [least permissions model](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-permissions?view=azure-devops&tabs=preview-page), as this [doc](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-permissions?view=azure-devops&tabs=preview-page) describes:

  > User accounts that are assigned to more than one security group are restricted to those permissions granting the least access. 

## Solution 

To get the behavior expect, we need to have **_three_** AAD groups per domain, for example:

- veggies-all
- veggies-dev
- veggies-admin

In this way, we can avoid overlapping role assignments that result in unexpected behavior in Azure DevOps.

### Tasks

- [x] Terraform: create 3 AAD groups per domain
- [x] Terraform: update assignments, paying extra attention to "supermarket" collaboration scenario
- [x] Concept: update text

**Comment by julie-ng** [comment]
Closed by PR #13
